"use client";

import { FloatingNav } from "@/components/ui/floating-navbar";
import dynamic from "next/dynamic";
import { FaHome, FaUserAlt, FaEnvelope, FaTags } from "react-icons/fa";

const Footer = dynamic(() => import('@/components/footer').then((mod) => mod.Footer), { ssr: false }); 

export default function Home({ searchParams }: SearchParamProps) {
  const isAdmin = searchParams?.admin === "true";    

  const navItems = [
    {
      name: "Home",
      link: "/",
    },
    {
      name: "About",
      link: "/about",
    },
    {
      name: "Pricing",
      link: "/pricing",
    },
    {
      name: "Contact",
      link: "/contact",
    },
  ];

  const logo = "/assets/icons/logo-doctorsclub.svg";

  return (  
    <div className="relative w-full min-h-screen flex flex-col">
      {/* Add Floating Navbar */}
      <FloatingNav navItems={navItems} logo={logo} />   

      {/* Add margin to push content below the navbar */}
      <section className="flex flex-col items-center justify-center py-16 px-6 sm:px-8 lg:px-10 text-black dark:text-white mt-24 sm:mt-32 lg:mt-36">
        <h2 className="text-4xl font-bold text-center mt-14 mb-14 sm:text-3xl md:text-4xl lg:text-5xl bg-clip-text text-transparent bg-gradient-to-b from-neutral-800 via-neutral-700 to-neutral-700 dark:from-neutral-800 dark:via-white dark:to-white">
          Terms & Conditions
        </h2>

        <div className="max-w-4xl w-full text-left leading-relaxed text-base sm:text-sm md:text-lg dark:text-white">
          <p className="mb-4">Last updated: September 11, 2024</p>

          <p className="mb-6">
            These Terms and Conditions ("Terms") constitute a binding agreement
            between <strong>doctorsClub</strong> ("we", "us", or "our") and you
            ("you" or "your"). By using our website, platform, or services, you
            agree to comply with these Terms.
          </p>

          <h3 className="text-2xl font-semibold mt-6">1. Acceptance of Terms</h3>
          <p className="mb-6">
            By accessing the <strong>doctorsClub</strong> platform or using our
            services, you confirm that you have read, understood, and agreed to
            these Terms and any related policies (e.g., Privacy Policy). We
            reserve the right to modify these Terms at any time without prior
            notice. Continued use of the platform after any changes indicates
            your acceptance of the revised Terms.
          </p>

          <h3 className="text-2xl font-semibold mt-6">2. Platform Overview</h3>
          <p className="mb-6">
            <strong>doctorsClub</strong> is a platform that enables doctors to
            manage and track their patients’ daily health data, add new
            patients, and receive daily reports on patient status. By using the    
            platform, you agree to comply with all applicable rules, guidelines,
            and legal requirements regarding patient data management.
          </p>

          <h3 className="text-2xl font-semibold mt-6">3. User Responsibility</h3>
          <p className="mb-6">
            As a registered user, you are required to provide accurate,
            up-to-date, and complete information. You are responsible for
            maintaining the confidentiality of your account and for all actions
            taken under your account. Misuse of the platform or unauthorized use
            may result in suspension or legal action.
          </p>

          <h3 className="text-2xl font-semibold mt-6">4. Patient Data and Reports</h3>
          <p className="mb-6">
            The platform allows you to input, track, and manage patient data,
            including daily reports. You are responsible for ensuring that the
            data you input is accurate and up-to-date. We are not liable for any
            inaccuracies in patient information or misinterpretation of the data
            provided through our platform.
          </p>

          <h3 className="text-2xl font-semibold mt-6">5. Service Disclaimer</h3>
          <p className="mb-6">
            While we strive to ensure that the platform functions smoothly,
            neither we nor any third parties provide any warranty or guarantee
            regarding the accuracy, timeliness, performance, or completeness of
            the data and reports generated by the platform. Your use of the
            platform and its reports is at your own risk, and you are
            responsible for ensuring that the platform meets your professional
            requirements.
          </p>

          <h3 className="text-2xl font-semibold mt-6">6. Data Privacy and Security</h3>
          <p className="mb-6">
            We take the privacy of patient data seriously. By using the
            platform, you agree to comply with applicable privacy laws and
            guidelines when handling patient information. Unauthorized access,
            sharing, or misuse of patient data is prohibited and may result in
            termination of your account and legal consequences.
          </p>

          <h3 className="text-2xl font-semibold mt-6">7. Intellectual Property</h3>
          <p className="mb-6">
            The platform, including its content, design, and features, is owned
            by or licensed to us. Unauthorized reproduction, modification, or
            use of any part of the platform is prohibited. Trademarks and logos
            used within the platform that are not owned by us are acknowledged
            accordingly.
          </p>

          <h3 className="text-2xl font-semibold mt-6">8. Limitation of Liability</h3>
          <p className="mb-6">
            We are not liable for any direct or indirect loss or damage arising
            from the use of the platform or services, including but not limited
            to, errors in patient data or reports. You acknowledge that it is
            your responsibility to verify the accuracy of the information and
            reports provided by the platform.
          </p>

          <h3 className="text-2xl font-semibold mt-6">9. Links to Third-Party Websites</h3>
          <p className="mb-6">
            The platform may contain links to external websites for additional
            resources. These links are provided for convenience only, and we are
            not responsible for the content or practices of such third-party
            websites.
          </p>

          <h3 className="text-2xl font-semibold mt-6">10. Refund Policy</h3>
          <p className="mb-6">
            You may request a refund if we fail to provide the services as
            agreed. Refund requests must be made within the specified timeframe
            according to our refund policy. Late requests will not be eligible
            for a refund.
          </p>

          <h3 className="text-2xl font-semibold mt-6">11. Governing Law and Disputes</h3>
          <p className="mb-6">
            These Terms are governed by the laws of India. Any disputes arising
            from the use of the platform or services will be subject to the
            exclusive jurisdiction of the courts in Pune, Maharashtra.
          </p>
        </div>
      </section>

      {/* Footer Section */}
      <Footer />
    </div>
  );
}   